### ISSUE TITLE
Declaring WireVectors named "tmp"

### ISSUE THREAD

**Issue by kyliehuch** [UCSBarchlab/PyRTL#257]
PyRTL throws the following error if you explicitly declare any WireVectors named "tmp":

<img width="569" alt="screen shot 2019-03-01 at 2 12 36 pm" src="https://user-images.githubusercontent.com/35501879/53669517-2d6f3080-3c2c-11e9-8cc9-f340465d8199.png">

**Comment by timsherwood** [comment]
There is not an easy way to catch this error because both internal and external functions call the wirevector constructors, and sometimes you need to make a tmp wire by name.  Instead we can improve the error message that sanity check gives you to mention the issue with tmp and const_ in particular.
