### ISSUE TITLE
Wavedrom output issues

### ISSUE THREAD

**Issue by ti6wb** [UCSBarchlab/PyRTL#273]
Hello, everybody,
I've only been using PyRTL for a few days and I think it's wonderful, but I think I found a bug in the creation of wavedrom timings. Enclosed you find the source code for an example where the error occurs and also the two timings (ASCII output, which looks correct and WaveDrom timing, which doesn't fit).

Best, Wolfgang

[gcd.zip](https://github.com/UCSBarchlab/PyRTL/files/4387432/gcd.zip)

![gcd2](https://user-images.githubusercontent.com/5501147/77651839-a7780300-6f6d-11ea-9d40-64d8eaa654db.png)
![gcd1](https://user-images.githubusercontent.com/5501147/77651845-a8109980-6f6d-11ea-9c39-40d577d3c3ef.png)

**Comment by mdko** [comment]
This appears to have been fixed in the last year in one of the various visualization updates we've pushed (note that there's currently an unrelated rendering issue in Jupyter notebooks (for any ipython output, not just this) when viewed on mybinder.org, but if you run it from the anaconda distribution, you should be able to see it correctly).

![Screen Shot 2021-09-25 at 2 20 13 AM](https://user-images.githubusercontent.com/2482771/134766480-c048d363-fee8-4c95-8d13-d4c75cd85e57.png)
